using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.ComponentModel;
using System.Drawing;


namespace ToliyGuitarSchoolHelper
{
    public partial class NameChord : Form
    {

        private IContainer components = null;


        private void InitializeComponent()
        {
            btnAccept = new Button();
            txbBase = new TextBox();
            lblBase = new Label();
            chbBaseFlat = new CheckBox();
            chbBaseSharp = new CheckBox();
            lblMain = new Label();
            txbMain = new TextBox();
            chbMainSharp = new CheckBox();
            chbMainFlat = new CheckBox();
            chbMinor = new CheckBox();
            lblMaj = new Label();
            txbMaj = new TextBox();
            lblSuperScript = new Label();
            txbSuper = new TextBox();
            chbDiminished = new CheckBox();
            chbHalfDiminished = new CheckBox();
            lblSuspend = new Label();
            txbSuspend = new TextBox();
            lblAdd = new Label();
            txbAdd = new TextBox();
            lblVersion = new Label();
            txbVersion = new TextBox();
            groupBox1 = new GroupBox();
            txbFilenameSuffix = new TextBox();
            label1 = new Label();
            groupBox1.SuspendLayout();
            SuspendLayout();
            btnAccept.Location = new Point(124, 331);
            btnAccept.Name = "btnAccept";
            btnAccept.Size = new Size(75, 23);
            btnAccept.TabIndex = 1;
            btnAccept.Text = "Принять";
            btnAccept.UseVisualStyleBackColor = true;
            btnAccept.Click += new EventHandler(btnAccept_Click);
            txbBase.Location = new Point(60, 49);
            txbBase.Name = "txbBase";
            txbBase.Size = new Size(44, 20);
            txbBase.TabIndex = 2;
            lblBase.AutoSize = true;
            lblBase.Location = new Point(8, 39);
            lblBase.Name = "lblBase";
            lblBase.Size = new Size(34, 13);
            lblBase.TabIndex = 3;
            lblBase.Text = "Base:";
            chbBaseFlat.AutoSize = true;
            chbBaseFlat.Location = new Point(128, 51);
            chbBaseFlat.Name = "chbBaseFlat";
            chbBaseFlat.RightToLeft = RightToLeft.Yes;
            chbBaseFlat.Size = new Size(40, 17);
            chbBaseFlat.TabIndex = 6;
            chbBaseFlat.Text = "flat";
            chbBaseFlat.UseVisualStyleBackColor = true;
            chbBaseSharp.AutoSize = true;
            chbBaseSharp.Location = new Point(189, 51);
            chbBaseSharp.Name = "chbBaseSharp";
            chbBaseSharp.RightToLeft = RightToLeft.Yes;
            chbBaseSharp.Size = new Size(52, 17);
            chbBaseSharp.TabIndex = 7;
            chbBaseSharp.Text = "sharp";
            chbBaseSharp.UseVisualStyleBackColor = true;
            lblMain.AutoSize = true;
            lblMain.Location = new Point(9, 89);
            lblMain.Name = "lblMain";
            lblMain.Size = new Size(33, 13);
            lblMain.TabIndex = 9;
            lblMain.Text = "Main:";
            txbMain.Location = new Point(60, 98);
            txbMain.Name = "txbMain";
            txbMain.Size = new Size(44, 20);
            txbMain.TabIndex = 8;
            chbMainSharp.AutoSize = true;
            chbMainSharp.Location = new Point(189, 101);
            chbMainSharp.Name = "chbMainSharp";
            chbMainSharp.RightToLeft = RightToLeft.Yes;
            chbMainSharp.Size = new Size(52, 17);
            chbMainSharp.TabIndex = 11;
            chbMainSharp.Text = "sharp";
            chbMainSharp.UseVisualStyleBackColor = true;
            chbMainFlat.AutoSize = true;
            chbMainFlat.Location = new Point(128, 101);
            chbMainFlat.Name = "chbMainFlat";
            chbMainFlat.RightToLeft = RightToLeft.Yes;
            chbMainFlat.Size = new Size(40, 17);
            chbMainFlat.TabIndex = 10;
            chbMainFlat.Text = "flat";
            chbMainFlat.UseVisualStyleBackColor = true;
            chbMinor.AutoSize = true;
            chbMinor.Location = new Point(8, 132);
            chbMinor.Name = "chbMinor";
            chbMinor.RightToLeft = RightToLeft.Yes;
            chbMinor.Size = new Size(55, 17);
            chbMinor.TabIndex = 14;
            chbMinor.Text = "Minor:";
            chbMinor.UseVisualStyleBackColor = true;
            lblMaj.AutoSize = true;
            lblMaj.Location = new Point(122, 146);
            lblMaj.Name = "lblMaj";
            lblMaj.Size = new Size(27, 13);
            lblMaj.TabIndex = 16;
            lblMaj.Text = "Maj:";
            txbMaj.Location = new Point(159, 143);
            txbMaj.Name = "txbMaj";
            txbMaj.Size = new Size(44, 20);
            txbMaj.TabIndex = 15;
            lblSuperScript.AutoSize = true;
            lblSuperScript.Location = new Point(8, 175);
            lblSuperScript.Name = "lblSuperScript";
            lblSuperScript.Size = new Size(38, 13);
            lblSuperScript.TabIndex = 18;
            lblSuperScript.Text = "Super:";
            txbSuper.Location = new Point(59, 185);
            txbSuper.Name = "txbSuper";
            txbSuper.Size = new Size(44, 20);
            txbSuper.TabIndex = 17;
            chbDiminished.AutoSize = true;
            chbDiminished.Location = new Point(124, 187);
            chbDiminished.Name = "chbDiminished";
            chbDiminished.RightToLeft = RightToLeft.Yes;
            chbDiminished.Size = new Size(75, 17);
            chbDiminished.TabIndex = 19;
            chbDiminished.Text = "diminished";
            chbDiminished.UseVisualStyleBackColor = true;
            chbHalfDiminished.AutoSize = true;
            chbHalfDiminished.Location = new Point(214, 187);
            chbHalfDiminished.Name = "chbHalfDiminished";
            chbHalfDiminished.RightToLeft = RightToLeft.Yes;
            chbHalfDiminished.Size = new Size(95, 17);
            chbHalfDiminished.TabIndex = 20;
            chbHalfDiminished.Text = "half-diminished";
            chbHalfDiminished.UseVisualStyleBackColor = true;
            lblSuspend.AutoSize = true;
            lblSuspend.Location = new Point(8, 217);
            lblSuspend.Name = "lblSuspend";
            lblSuspend.Size = new Size(28, 13);
            lblSuspend.TabIndex = 22;
            lblSuspend.Text = "Sus:";
            txbSuspend.Location = new Point(59, 230);
            txbSuspend.Name = "txbSuspend";
            txbSuspend.Size = new Size(44, 20);
            txbSuspend.TabIndex = 21;
            lblAdd.AutoSize = true;
            lblAdd.Location = new Point(117, 233);
            lblAdd.Name = "lblAdd";
            lblAdd.Size = new Size(29, 13);
            lblAdd.TabIndex = 24;
            lblAdd.Text = "Add:";
            lblAdd.Click += new EventHandler(lblAdd_Click);
            txbAdd.Location = new Point(159, 230);
            txbAdd.Name = "txbAdd";
            txbAdd.Size = new Size(44, 20);
            txbAdd.TabIndex = 23;
            txbAdd.TextChanged += new EventHandler(textBox5_TextChanged);
            lblVersion.AutoSize = true;
            lblVersion.Location = new Point(212, 233);
            lblVersion.Name = "lblVersion";
            lblVersion.Size = new Size(45, 13);
            lblVersion.TabIndex = 26;
            lblVersion.Text = "Version:";
            txbVersion.Location = new Point(264, 230);
            txbVersion.Name = "txbVersion";
            txbVersion.Size = new Size(44, 20);
            txbVersion.TabIndex = 25;
            groupBox1.Controls.Add(label1);
            groupBox1.Controls.Add(txbFilenameSuffix);
            groupBox1.Controls.Add(lblSuspend);
            groupBox1.Controls.Add(lblSuperScript);
            groupBox1.Controls.Add(chbMinor);
            groupBox1.Controls.Add(lblMain);
            groupBox1.Controls.Add(lblBase);
            groupBox1.Location = new Point(12, 13);
            groupBox1.Name = "groupBox1";
            groupBox1.Size = new Size(309, 302);
            groupBox1.TabIndex = 27;
            groupBox1.TabStop = false;
            groupBox1.Text = "Компоненты аккорда";
            txbFilenameSuffix.Location = new Point(95, 263);
            txbFilenameSuffix.Name = "txbFilenameSuffix";
            txbFilenameSuffix.Size = new Size(201, 20);
            txbFilenameSuffix.TabIndex = 23;
            label1.AutoSize = true;
            label1.Location = new Point(8, 266);
            label1.Name = "label1";
            label1.Size = new Size(81, 13);
            label1.TabIndex = 24;
            label1.Text = "Filename Suffix:";
            AutoScaleDimensions = new SizeF(6f, 13f);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(333, 366);
            Controls.Add(chbBaseSharp);
            Controls.Add(lblVersion);
            Controls.Add(txbVersion);
            Controls.Add(lblAdd);
            Controls.Add(txbAdd);
            Controls.Add(txbSuspend);
            Controls.Add(chbHalfDiminished);
            Controls.Add(chbDiminished);
            Controls.Add(txbSuper);
            Controls.Add(lblMaj);
            Controls.Add(txbMaj);
            Controls.Add(chbMainSharp);
            Controls.Add(chbMainFlat);
            Controls.Add(txbMain);
            Controls.Add(chbBaseFlat);
            Controls.Add(txbBase);
            Controls.Add(btnAccept);
            Controls.Add(groupBox1);
            MaximizeBox = false;
            MinimizeBox = false;
            Name = "NameChord";
            StartPosition = FormStartPosition.CenterParent;
            Text = "Название Аккорда";
            Load += new EventHandler(NameChord_Load);
            groupBox1.ResumeLayout(false);
            groupBox1.PerformLayout();
            ResumeLayout(false);
            PerformLayout();
        }

        protected override void Dispose(bool disposing)
        {
            if ((!disposing ? false : this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }


        private Button btnAccept;
        private TextBox txbBase;
        private Label lblBase;
        private CheckBox chbBaseFlat;
        private CheckBox chbBaseSharp;
        private Label lblMain;
        private TextBox txbMain;
        private CheckBox chbMainSharp;
        private CheckBox chbMainFlat;
        private CheckBox chbMinor;
        private Label lblMaj;
        private TextBox txbMaj;
        private Label lblSuperScript;
        private TextBox txbSuper;
        private CheckBox chbDiminished;
        private CheckBox chbHalfDiminished;
        private Label lblSuspend;
        private TextBox txbSuspend;
        private Label lblAdd;
        private TextBox txbAdd;
        private Label lblVersion;
        private TextBox txbVersion;
        private GroupBox groupBox1;
        private Label label1;
        private TextBox txbFilenameSuffix;


    }
}
